lib/web/router.ex
defmodule BorsNG.Router do
  @moduledoc """
  This module maps from URLs to controllers and plugs.
  It layers on pre-filters, primarily the session, flash,
  CSRF protection, secure headers,
  and user authentication part of the session.
  """

  use BorsNG.Web, :router
  alias BorsNG.Database

  pipeline :browser_page do
    plug :accepts, ["html"]
  end

  pipeline :browser_ajax do
    plug :accepts, ["json"]
  end

  pipeline :browser_session do
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :get_current_user
  end

  pipeline :browser_login do
    plug :force_current_user
  end

  pipeline :browser_admin do
    plug :force_current_user_admin
  end

  pipeline :webhook do
    plug Plug.Parsers, parsers: [:json], json_decoder: Poison
  end

  scope "/", BorsNG do
    pipe_through :browser_page
    pipe_through :browser_session
    pipe_through :browser_login

    get "/", PageController, :index
  end

  scope "/repositories", BorsNG do
    pipe_through :browser_page
    pipe_through :browser_session
    pipe_through :browser_login

    get "/", ProjectController, :index
    get "/:id", ProjectController, :show
    get "/:id/settings", ProjectController, :settings
    put "/:id/settings/branches", ProjectController, :update_branches
    put "/:id/settings/reviewer", ProjectController, :update_reviewer_settings
    put "/:id/settings/member", ProjectController, :update_member_settings
    delete "/:id/batches/incomplete", ProjectController, :cancel_all
    post "/:id/reviewer", ProjectController, :add_reviewer
    post "/:id/member", ProjectController, :add_member
    get "/:id/add-reviewer/:login", ProjectController, :confirm_add_reviewer
    put "/:id/synchronize", ProjectController, :synchronize
    get "/:id/log", ProjectController, :log
    get "/:id/log_page", ProjectController, :log_page
    delete "/:id/reviewer/:user_id", ProjectController, :remove_reviewer
    delete "/:id/member/:user_id", ProjectController, :remove_member
  end

  scope "/admin", BorsNG do
    pipe_through :browser_page
    pipe_through :browser_session
    pipe_through :browser_login
    pipe_through :browser_admin

    get "/", AdminController, :index
    get "/orphans", AdminController, :orphans
    get "/project", AdminController, :project_by_name
    get "/dup-patches", AdminController, :dup_patches
    get "/crashes", AdminController, :crashes
    post "/synchronize-all-installations", AdminController,
         :synchronize_all_installations
  end

  scope "/auth", BorsNG do
    pipe_through :browser_ajax
    pipe_through :browser_session
    get "/socket-token", AuthController, :socket_token
  end

  scope "/auth", BorsNG do
    pipe_through :browser_page
    pipe_through :browser_session

    get "/logout", AuthController, :logout
    get "/:provider", AuthController, :index
    get "/:provider/callback", AuthController, :callback
  end

  scope "/webhook", BorsNG do
    pipe_through :webhook
    post "/:provider", WebhookController, :webhook
  end

  # Fetch the current user from the session and add it to `conn.assigns`. This
  # will allow you to have access to the current user in your views with
  # `@current_user`.

  defp get_current_user(conn, _) do
    user_id = Plug.Conn.get_session(conn, :current_user)
    if is_nil user_id do
      conn
    else
      conn
      |> assign(:user, Database.Repo.get(Database.User, user_id))
      |> assign(:avatar_url, Plug.Conn.get_session(conn, :avatar_url))
    end
  end

  defp force_current_user(conn, _) do
    if is_nil conn.assigns[:user] do
      conn
      |> Plug.Conn.put_session(:auth_redirect_to, conn.request_path)
      |> Phoenix.Controller.redirect(to: "/auth/github")
      |> halt
    else
      conn
    end
  end

  defp force_current_user_admin(conn, _) do
    case conn do
      %{assigns: %{user: %{is_admin: true}}} -> conn
      _ ->
        conn
        |> Plug.Conn.send_resp(403, "Not allowed.")
        |> halt
    end
  end
end

lib/web/views/layout_view.ex
defmodule BorsNG.LayoutView do
  @moduledoc """
  The common wrapper for all pages; namely,
  the bar along the top and the disclaimer along the bottom.
  """

  use BorsNG.Web, :view

  def get_version do
    get_commit() || get_tag()
  end

  def get_commit do
    hash = get_heroku_commit() || get_git_commit()
    if hash do
      {String.slice(hash, 0..6), hash}
    else
      nil
    end
  end

  def get_tag do
    v = get_release_version()
    {v, "v#{v}"}
  end

  def get_heroku_commit do
    System.get_env("HEROKU_SLUG_COMMIT")
  end

  def get_git_commit do
    ".git/HEAD"
    |> File.read()
    |> case do
      {:ok, "ref: " <> branch} ->
        branch = String.trim(branch)
        case File.read(".git/" <> branch) do
          {:ok, commit} -> String.trim(commit)
          _ -> nil
        end
      {:ok, commit} -> String.trim(commit)
      _ -> nil
    end
  end

  def get_release_version do
    case :application.get_key(:vsn) do
      {:ok, vsn} -> List.to_string(vsn)
      _ -> nil
    end
  end

  def get_header_html do
    Confex.fetch_env!(:bors, BorsNG)[:dashboard_header_html]
  end

  def get_footer_html do
    Confex.fetch_env!(:bors, BorsNG)[:dashboard_footer_html]
  end
end

lib/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>bors</title>
    <link rel="apple-touch-icon" sizes="180x180" href="/images/apple-touch-icon.png">
    <link rel="icon" type="image/svg+xml" title="bors eye" href="/images/i.svg">
    <link rel="icon" type="image/png" sizes="32x32" href="/images/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/images/favicon-16x16.png">
    <link rel="manifest" href="/images/manifest.json">
    <link rel="mask-icon" href="/images/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="theme-color" content="#eeeeee">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
<%= if not is_nil(@conn.assigns[:user]) do %>
    <meta name="bors-current-user" content="<%= @conn.assigns.user.id %>">
<% end %>
  </head>

  <body>
    <div id=alert-container>
      <%= if assigns[:project] do %>
      <div hidden="hidden" id="js--on-project-ping" data-bors-project-id="<%= @project.id %>" role="alert" class="alert js--closable">
      This page is out of date. <a href="">Reload</a>
      </div>
      <% end %>
      <%= if not is_nil get_flash(@conn, :ok) do %>
      <div role="alert" class="alert alert--ok js--closable">
      <%= get_flash(@conn, :ok) %>
      </div>
      <% end %>
      <%= if not is_nil get_flash(@conn, :error) do %>
      <div role="alert" class="alert alert--error js--closable">
      <%= get_flash(@conn, :error) %>
      </div>
      <% end %>
    </div>
    <header role="banner">
      <div class="wrapper wrapper--mini">
        <a id=header-logo href="<%= page_path(@conn, :index) %>"><img alt="bors" src='<%= static_path(@conn, "/images/a.svg") %>' width="90" height="25"></a>
        <span id=header-sections class=hide-on-narrow>
          <%= {:safe, get_header_html()} %>
        </span>
        <span id=header-user>
<%= if is_nil @conn.assigns[:user] do %>
          <a class=header-link href='<%= auth_path(@conn, :index, "github") %>'>Log in with GitHub</a>
<% else %>
  <%= if @conn.path_info == ["repositories"] do %>
          <b class="header-link hide-on-narrow">Repositories</b>
  <% else %>
          <a class="header-link hide-on-narrow" href="<%= project_path(@conn, :index) %>">Repositories</a>
  <% end %>
          <a href="#user-dropdown" class="header-link-container drop-down-menu--toggler">
            <img width=25 height=25 class="no-outline-on-focus" src="<%= @conn.assigns.avatar_url %>" alt="" role="presentation">
            <span class=header-link><%= @conn.assigns.user.login %> ▾</span>
          </a>
<% end %>
<%= if not is_nil @conn.assigns[:user] do %>
          <div class=drop-down-menu--right><div id="user-dropdown" class="drop-down-menu">
  <%= if @conn.assigns.user.is_admin do %>
            <a href="<%= admin_path(@conn, :index) %>">Admin</a>
  <% end %>
            <a class=show-on-narrow href="<%= project_path(@conn, :index) %>">Repositories</a>
            <a href="<%= auth_path(@conn, :logout) %>">Log out</a>
<% end %>
          </div></div>
        </span>
      </div>
    </header>

    <%= render @view_module, @view_template, assigns %>

    <footer role=navigation class=show-on-narrow>
      <div class=wrapper>
          <%= {:safe, get_header_html()} %>
      </div>
    </footer>
    <footer role=note>
      <p class=wrapper>
        <span id=footer-version>
          Build:
          <a href="https://github.com/bors-ng/bors-ng/tree/<%= elem(get_version(), 1) %>">
            <%= elem(get_version(), 0) %>
          </a>
        </span>
        <%= {:safe, get_footer_html()} %>
      </p>
    </footer>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>