lib/web/router.ex
defmodule BorsNG.Router do
  @moduledoc """
  This module maps from URLs to controllers and plugs.
  It layers on pre-filters, primarily the session, flash,
  CSRF protection, secure headers,
  and user authentication part of the session.
  """

  use BorsNG.Web, :router
  alias BorsNG.Database

  pipeline :browser_page do
    plug :accepts, ["html"]
  end

  pipeline :browser_ajax do
    plug :accepts, ["json"]
  end

  pipeline :browser_session do
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :get_current_user
  end

  pipeline :browser_login do
    plug :force_current_user
  end

  pipeline :browser_admin do
    plug :force_current_user_admin
  end

  pipeline :webhook do
    plug Plug.Parsers, parsers: [:json], json_decoder: Poison
  end

  scope "/", BorsNG do
    pipe_through :browser_page
    pipe_through :browser_session
    pipe_through :browser_login

    get "/", PageController, :index
  end

  scope "/repositories", BorsNG do
    pipe_through :browser_page
    pipe_through :browser_session
    pipe_through :browser_login

    get "/", ProjectController, :index
    get "/:id", ProjectController, :show
    get "/:id/settings", ProjectController, :settings
    put "/:id/settings/branches", ProjectController, :update_branches
    put "/:id/settings/reviewer", ProjectController, :update_reviewer_settings
    put "/:id/settings/member", ProjectController, :update_member_settings
    delete "/:id/batches/incomplete", ProjectController, :cancel_all
    post "/:id/reviewer", ProjectController, :add_reviewer
    post "/:id/member", ProjectController, :add_member
    get "/:id/add-reviewer/:login", ProjectController, :confirm_add_reviewer
    put "/:id/synchronize", ProjectController, :synchronize
    get "/:id/log", ProjectController, :log
    get "/:id/log_page", ProjectController, :log_page
    delete "/:id/reviewer/:user_id", ProjectController, :remove_reviewer
    delete "/:id/member/:user_id", ProjectController, :remove_member
  end

  scope "/admin", BorsNG do
    pipe_through :browser_page
    pipe_through :browser_session
    pipe_through :browser_login
    pipe_through :browser_admin

    get "/", AdminController, :index
    get "/orphans", AdminController, :orphans
    get "/project", AdminController, :project_by_name
    get "/dup-patches", AdminController, :dup_patches
    get "/crashes", AdminController, :crashes
    post "/synchronize-all-installations", AdminController,
         :synchronize_all_installations
  end

  scope "/auth", BorsNG do
    pipe_through :browser_ajax
    pipe_through :browser_session
    get "/socket-token", AuthController, :socket_token
  end

  scope "/auth", BorsNG do
    pipe_through :browser_page
    pipe_through :browser_session

    get "/logout", AuthController, :logout
    get "/:provider", AuthController, :index
    get "/:provider/callback", AuthController, :callback
  end

  scope "/webhook", BorsNG do
    pipe_through :webhook
    post "/:provider", WebhookController, :webhook
  end

  # Fetch the current user from the session and add it to `conn.assigns`. This
  # will allow you to have access to the current user in your views with
  # `@current_user`.

  defp get_current_user(conn, _) do
    user_id = Plug.Conn.get_session(conn, :current_user)
    if is_nil user_id do
      conn
    else
      conn
      |> assign(:user, Database.Repo.get(Database.User, user_id))
      |> assign(:avatar_url, Plug.Conn.get_session(conn, :avatar_url))
    end
  end

  defp force_current_user(conn, _) do
    if is_nil conn.assigns[:user] do
      conn
      |> Plug.Conn.put_session(:auth_redirect_to, conn.request_path)
      |> Phoenix.Controller.redirect(to: "/auth/github")
      |> halt
    else
      conn
    end
  end

  defp force_current_user_admin(conn, _) do
    case conn do
      %{assigns: %{user: %{is_admin: true}}} -> conn
      _ ->
        conn
        |> Plug.Conn.send_resp(403, "Not allowed.")
        |> halt
    end
  end
end

lib/web/controllers/project_controller.ex
defmodule BorsNG.ProjectController do
  @moduledoc """
  Shows a list of repositories, a single repository,
  and the repository's settings page.

  n.b.
  We call it a project internally, though it corresponds
  to a GitHub repository. This is to avoid confusing
  a GitHub repo with an Ecto repo.
  """

  use BorsNG.Web, :controller

  alias BorsNG.Worker.Batcher
  alias BorsNG.Database.Context.Dashboard
  alias BorsNG.Database.Context.Permission
  alias BorsNG.Database.Repo
  alias BorsNG.Database.LinkMemberProject
  alias BorsNG.Database.LinkUserProject
  alias BorsNG.Database.Project
  alias BorsNG.Database.Batch
  alias BorsNG.Database.Crash
  alias BorsNG.Database.Patch
  alias BorsNG.Database.User
  alias BorsNG.GitHub
  alias BorsNG.Worker.Syncer

  # Auto-grab the project and check the permissions

  def action(conn, _) do
    do_action(conn, action_name(conn), conn.params)
  end

  defp do_action(conn, action, %{"id" => id} = params) do
    allow_private_repos = Confex.fetch_env!(
      :bors, BorsNG)[:allow_private_repos]
    project = Project
    |> from(preload: [:installation])
    |> Repo.get!(id)
    admin? = conn.assigns.user.is_admin
    mode = conn.assigns.user
    |> Permission.get_permission(project)
    |> case do
      _ when admin? -> :rw
      :reviewer -> :rw
      :member -> :ro
      _ when not allow_private_repos -> :ro
      _ -> raise BorsNG.PermissionDeniedError
    end
    apply(__MODULE__, action, [conn, mode, project, params])
  end
  defp do_action(conn, action, params) do
    apply(__MODULE__, action, [conn, params])
  end

  # The actual handlers
  # Two-item ones have a project ID inputed
  # One-item ones don't

  def index(conn, %{"mode" => "reviewer"}) do
    index_(conn, :reviewer)
  end
  def index(conn, %{"mode" => "member"}) do
    index_(conn, :member)
  end
  def index(conn, _params) do
    index_(conn, :all)
  end

  defp index_(conn, filter) do
    projects = Dashboard.my_projects(conn.assigns.user.id, filter)
    render conn, "index.html", projects: projects, filter: filter
  end

  defp batch_info(batch) do
    %{
      commit: batch.commit,
      patches: Repo.all(Patch.all_for_batch(batch.id)),
      state: batch.state}
  end

  def show(conn, mode, project, _params) do
    batches = project.id
    |> Batch.all_for_project(:incomplete)
    |> Repo.all()
    |> Enum.map(&batch_info/1)
    unbatched_patches = project.id
    |> Patch.all_for_project(:awaiting_review)
    |> Repo.all()
    is_synchronizing = match?(
      [{_, _}],
      Registry.lookup(Syncer.Registry, project.id))
    render conn, "show.html",
      project: project,
      batches: batches,
      is_synchronizing: is_synchronizing,
      unbatched_patches: unbatched_patches,
      mode: mode
  end

  def settings(_, :ro, _, _), do: raise BorsNG.PermissionDeniedError
  def settings(conn, :rw, project, _params) do
    reviewers = Permission.list_users_for_project(:reviewer, project.id)
    |> Enum.sort_by(fn %User{login: login} ->
      case conn.assigns[:user].login do
        ^login -> ""
        _ -> login
      end
    end)
    members = Permission.list_users_for_project(:member, project.id)
    |> Enum.sort_by(fn %User{login: login} ->
      case conn.assigns[:user].login do
        ^login -> ""
        _ -> login
      end
    end)
    render conn, "settings.html",
      project: project,
      reviewers: reviewers,
      members: members,
      current_user_id: conn.assigns.user.id,
      update_reviewer_settings:
        Project.changeset_reviewer_settings(project),
      update_member_settings: Project.changeset_member_settings(project),
      update_branches: Project.changeset_branches(project)
  end

  defp seek_batch_log(project) do
    project.id
    |> Batch.seek_for_project(10)
    |> Repo.all()
    |> Enum.map(fn
      %Batch{id: id} = batch ->
        %{batch | patches: Repo.all(Patch.all_for_batch(id))}
    end)
  end

  defp seek_batch_log(project, "-1", _latest_updated_at), do: seek_batch_log(project)
  defp seek_batch_log(project, highest_id, latest_updated_at) do
    project.id
    |> Batch.seek_for_project(highest_id, latest_updated_at, 10)
    |> Repo.all()
    |> Enum.map(fn
      %Batch{id: id} = batch ->
        %{batch | patches: Repo.all(Patch.all_for_batch(id))}
    end)
  end

  defp seek_crash_log(project), do: Repo.all(Crash.seek_for_project(project.id, 10))
  defp seek_crash_log(project, "-1", _latest_updated_at), do: seek_crash_log(project)
  defp seek_crash_log(project, highest_id, latest_updated_at) do
    project.id
    |> Crash.seek_for_project(highest_id, latest_updated_at, 10)
    |> Repo.all()
  end

  defp seek_log(project) do
    batches = seek_batch_log(project)
    crashes = seek_crash_log(project)
    batches ++ crashes
    |> Enum.sort_by(fn %{updated_at: at} -> NaiveDateTime.to_iso8601(at) end)
    |> Enum.reverse()
    |> Enum.take(10)
  end

  defp seek_log(project, highest_batch_id, highest_crash_id, latest_updated_at) do
    batches = seek_batch_log(project, highest_batch_id, latest_updated_at)
    crashes = seek_crash_log(project, highest_crash_id, latest_updated_at)
    batches ++ crashes
    |> Enum.sort_by(fn %{updated_at: at} -> NaiveDateTime.to_iso8601(at) end)
    |> Enum.reverse()
    |> Enum.take(10)
  end

  def log(_, :ro, _, _), do: raise BorsNG.PermissionDeniedError
  def log(conn, :rw, project, _params) do
    render conn, "log.html",
      project: project,
      current_user_id: conn.assigns.user.id,
      entries: seek_log(project)
  end

  def log_page(_, :ro, _, _), do: raise BorsNG.PermissionDeniedError
  def log_page(conn, :rw, project, params) do
    batch_id = params["batch_id"]
    crash_id = params["crash_id"]
    updated_at = NaiveDateTime.from_iso8601!(params["updated_at"])
    conn
    |> put_layout(false)
    |> render "log_page.html",
      project: project, 
      entries: seek_log(project, batch_id, crash_id, updated_at)
  end

  def cancel_all(_, :ro, _, _), do: raise BorsNG.PermissionDeniedError
  def cancel_all(conn, :rw, project, _params) do
    project.id
    |> Batcher.Registry.get()
    |> Batcher.cancel_all()
    conn
    |> put_flash(:ok, "Canceled all running batches")
    |> redirect(to: project_path(conn, :show, project))
  end

  def update_reviewer_settings(_, :ro, _, _) do
    raise BorsNG.PermissionDeniedError
  end
  def update_reviewer_settings(conn, :rw, project, %{"project" => pdef}) do
    result = project
    |> Project.changeset_reviewer_settings(pdef)
    |> Repo.update()
    case result do
      {:ok, _} ->
        Syncer.start_synchronize_project(project.id)
        conn
        |> put_flash(:ok, "Successfully updated reviewer settings")
        |> redirect(to: project_path(conn, :settings, project))
      {:error, changeset} ->
        reviewers = Permission.list_users_for_project(:reviewer, project.id)
        members = Permission.list_users_for_project(:member, project.id)
        conn
        |> put_flash(:error, "Cannot update branches")
        |> render("settings.html",
          project: project,
          reviewers: reviewers,
          members: members,
          current_user_id: conn.assigns.user.id,
          update_reviewer_settings: changeset,
          update_member_settings: Project.changeset_member_settings(project),
          update_branches: Project.changeset_branches(project))
    end
  end

  def update_member_settings(_, :ro, _, _) do
    raise BorsNG.PermissionDeniedError
  end
  def update_member_settings(conn, :rw, project, %{"project" => pdef}) do
    result = project
    |> Project.changeset_member_settings(pdef)
    |> Repo.update()
    case result do
      {:ok, _} ->
        Syncer.start_synchronize_project(project.id)
        conn
        |> put_flash(:ok, "Successfully updated member settings")
        |> redirect(to: project_path(conn, :settings, project))
      {:error, changeset} ->
        reviewers = Permission.list_users_for_project(:reviewer, project.id)
        members = Permission.list_users_for_project(:member, project.id)
        conn
        |> put_flash(:error, "Cannot update branches")
        |> render("settings.html",
          project: project,
          reviewers: reviewers,
          members: members,
          current_user_id: conn.assigns.user.id,
          update_reviewer_settings:
            Project.changeset_reviewer_settings(project),
          update_member_settings: changeset,
          update_branches: Project.changeset_branches(project))
    end
  end

  def update_branches(_, :ro, _, _), do: raise BorsNG.PermissionDeniedError
  def update_branches(conn, :rw, project, %{"project" => pdef}) do
    result = project
    |> Project.changeset_branches(pdef)
    |> Repo.update()
    case result do
      {:ok, _} ->
        conn
        |> put_flash(:ok, "Successfully updated branches")
        |> redirect(to: project_path(conn, :settings, project))
      {:error, changeset} ->
        reviewers = Permission.list_users_for_project(:reviewer, project.id)
        members = Permission.list_users_for_project(:member, project.id)
        conn
        |> put_flash(:error, "Cannot update branches")
        |> render("settings.html",
          project: project,
          reviewers: reviewers,
          members: members,
          current_user_id: conn.assigns.user.id,
          update_reviewer_settings:
            Project.changeset_reviewer_settings(project),
          update_member_settings: Project.changeset_member_settings(project),
          update_branches: changeset)
    end
  end


  def add_reviewer(_, :ro, _, _), do: raise BorsNG.PermissionDeniedError
  def add_reviewer(conn, :rw, project, %{"reviewer" => %{"login" => ""}}) do
    conn
    |> put_flash(:error, "Please enter a GitHub user's nickname")
    |> redirect(to: project_path(conn, :settings, project))
  end
  def add_reviewer(conn, :rw, project, %{"reviewer" => %{"login" => login}}) do
    user = case Repo.get_by(User, login: login) do
      nil ->

lib/web/views/project_view.ex
defmodule BorsNG.ProjectView do
  @moduledoc """
  The list of repository's, and each individual repository page.

  n.b.
  We call it a project internally, though it corresponds
  to a GitHub repository. This is to avoid confusing
  a GitHub repo with an Ecto repo.
  """

  use BorsNG.Web, :view

  def stringify_state(state) do
    case state do
      :waiting  -> "Waiting to run"
      :running  -> "Running"
      :ok       -> "Succeeded"
      :error    -> "Failed"
      :canceled -> "Canceled"
      _         -> "Invalid"
    end
  end

  def truncate_commit(<<t :: binary - size(7), _ :: binary>>), do: t
  def truncate_commit(t) when is_binary(t), do: t
  def truncate_commit(nil), do: "[nil]"
  def truncate_commit(_), do: "[invalid]"

  def htmlify_naive_datetime(datetime) do
    [ "<td><time class=time-convert>",
      NaiveDateTime.to_iso8601(datetime),
      "+00:00</time></td>" ]
    |> Phoenix.HTML.raw()
  end
  @doc """
  Checks to see if there is an empty list then returns true
  """
  def empty?([]), do: true
  @doc """
  Checks to see if the variable is a list with elements then returns false. 
  """
  def empty?(list) when is_list(list) do
    false
  end
end

lib/web/templates/project/confirm-add-reviewer.html.eex
<nav>

<div class=wrapper>
  <a href="<%= Confex.fetch_env!(:bors, :html_github_root) %>/<%= @project.name %>/">
    <%= @project.name %>
  </a>
  ›
  <a href="<%= project_path(@conn, :settings, @project) %>">
    Settings
  </a>
  <h1>
  Add reviewer
  </h1>
</div>

</nav>

<main role=main><div class=wrapper>

<h2 class=header><%= @login %></h2>

<%= form_for @conn, project_path(@conn, :add_reviewer, @project.id), [as: :reviewer, class: "toolbar"], fn f -> %>
<%= hidden_input f, :login, value: @login %>
<%= submit "OK", class: "toolbar-item toolbar-item--add" %>
<%= link "Cancel", to: project_path(@conn, :settings, @project), class: "toolbar-item toolbar-item--remove" %>
<% end %>

</div></main>

lib/web/templates/project/index.html.eex
<main role=main><div class=wrapper>

<div class=toolbar>
  <a class=toolbar-item href="<%= BorsNG.Attrs.get_github_integration_url() %>">
    Add / Remove Repositories
  </a>
</div>
  <%= if empty? @projects do %>
    Nothing to see here!
  <% else %>

<table class="table">
  <tbody>
<%= for project <- @projects do %>
    <tr role=row>
      <td class="fill-link">
        <%= link project.name, to: project_path(@conn, :show, project) %>
      </td>
    </tr>
<% end %>
<% end %>
  </tbody>
</table>

</div></main>

lib/web/templates/project/log.html.eex
<nav>

<div class=wrapper>
  <h1>
    <a href="<%= Confex.fetch_env!(:bors, :html_github_root) %>/<%= @project.name %>/">
      <%= @project.name %>
    </a>
  </h1>
</div>

<div class=tabs role=navigation>
  <%= link "Pull requests", to: project_path(@conn, :show, @project), class: "tab" %>
  <span class="tab tab--active" aria-selected=true>History</span>
  <%= link "Settings", to: project_path(@conn, :settings, @project), class: "tab" %>
</div>

</nav>

<main role=main><div class=wrapper>

<table id="log-table" class="table">
  <tbody>
<%= render "log_page.html", project: @project, entries: @entries%>
  </tbody>
</table>

<div style="text-align: center;">
  <a id="log-request" href="">Older</a>
</div>

</div></main>

lib/web/templates/project/log_page.html.eex
<%= for entry <- @entries do %>
  <%= case entry do %>
  <% %BorsNG.Database.Crash{id: id, component: component, crash: crash, updated_at: updated_at} -> %>
    <tr role=row id="crash-<%= id %>" data-id="<%= id %>" data-datetime="<%= updated_at %>">
      <td><%= htmlify_naive_datetime(updated_at) %></td>
      <td>Crash</td>
      <td><%= component %></td>
      <td><pre><code><%= crash %></code></pre></td>
    </tr>
  <% %BorsNG.Database.Batch{id: id, state: state, patches: patches, updated_at: updated_at} -> %>
    <tr role=row id="batch-<%= id %>" data-id="<%= id %>" data-datetime="<%= updated_at %>">
      <td><%= htmlify_naive_datetime(updated_at) %></td>
      <td>Batch</td>
      <td><%= stringify_state(state) %></td>
      <td>
      <%= for patch <- patches do %>
        <a href="<%= Confex.fetch_env!(:bors, :html_github_root) %>/<%= @project.name %>/pull/<%= patch.pr_xref %>">#<%= patch.pr_xref %></a>
      <% end %>
      </td>
    </tr>
  <% end %>
<% end %>

lib/web/templates/project/settings.html.eex
<nav>

<div class=wrapper>
  <h1>
    <a href="<%= Confex.fetch_env!(:bors, :html_github_root) %>/<%= @project.name %>/">
      <%= @project.name %>
    </a>
  </h1>
</div>

<div class=tabs role=navigation>
  <%= link "Pull requests", to: project_path(@conn, :show, @project), class: "tab" %>
  <%= link "History", to: project_path(@conn, :log, @project), class: "tab" %>
  <span class="tab tab--active" aria-selected=true>Settings</span>
</div>

</nav>

<main role=main>

<div class=wrapper><section class=split>

<section class=split-item>
<h2 class=header>Reviewers</h2>
<p>permission to run any command, and to change repository settings</p>
<%= form_for @update_reviewer_settings, project_path(@conn, :update_reviewer_settings, @project), [as: :project], fn f -> %>
  <label for=project_auto_reviewer_required_perm>Synchronize</label>
  <div class=toolbar>
    <%= select f, :auto_reviewer_required_perm, BorsNG.Database.ProjectPermission.select_list %>
    <%= submit "Update", class: "toolbar-item" %>
  </div>
<% end %>
<table class="table">
  <tbody>
<%= for reviewer <- @reviewers do %>
    <tr role=row>
      <td>
        <%= reviewer.login %>
      </td>
<%= if !@project.auto_reviewer_required_perm do %>
      <%= form_for @conn, project_path(@conn, :remove_reviewer, @project.id, reviewer.id), [as: :reviewer, method: :delete], fn _ -> %>
      <td class="fill-link">
  <%= if reviewer.id != @current_user_id do %>
          <%= submit "Remove", title: "Remove reviewer", class: "table-button table-button--remove" %>
  <% end %>
      </td>
      <% end %>
<% end %>
    </tr>
<% end %>
<%= if !@project.auto_reviewer_required_perm do %>
    <tr role=row>
      <%= form_for @conn, project_path(@conn, :add_reviewer, @project.id), [as: :reviewer], fn f -> %>
      <td>
        <%= text_input f, :login, placeholder: "GitHub login" %>
      </td>
      <td class="fill-link table-button-col">
        <%= submit "Add", title: "Add reviewer", class: "table-button table-button--add" %>
      </td>
      <% end %>
    </tr>
<% end %>
  </tbody>
</table>
</section> <!-- class=split-item -->

<section class=split-item>
<h2 class=header>Members</h2>
<p>permission to run the <code>try</code> and <code>retry</code> commands</p>
<%= form_for @update_member_settings, project_path(@conn, :update_member_settings, @project), [as: :project], fn f -> %>
  <label for=project_auto_member_required_perm>Synchronize</label>
  <div class=toolbar>
    <%= select f, :auto_member_required_perm, BorsNG.Database.ProjectPermission.select_list %>
    <%= submit "Update", class: "toolbar-item" %>
  </div>
<% end %>
<table class="table">
  <tbody>
<%= for member <- @members do %>
    <tr role=row>
      <td>
        <%= member.login %>
      </td>
<%= if !@project.auto_member_required_perm do %>
      <%= form_for @conn, project_path(@conn, :remove_member, @project.id, member.id), [as: :member, method: :delete], fn _ -> %>
      <td class="fill-link">
        <%= submit "Remove", title: "Remove member", class: "table-button table-button--remove" %>
      </td>
      <% end %>
<% end %>
    </tr>
<% end %>
<%= if !@project.auto_member_required_perm do %>
    <tr role=row>
      <%= form_for @conn, project_path(@conn, :add_member, @project.id), [as: :member], fn f -> %>
      <td>
        <%= text_input f, :login, placeholder: "GitHub login" %>
      </td>
      <td class="fill-link table-button-col">
        <%= submit "Add", title: "Add member", class: "table-button table-button--add" %>
      </td>
      <% end %>
    </tr>
<% end %>
  </tbody>
</table>
</section> <!-- class=split-item -->

</section></div> <!-- class=split -->

<div class=wrapper><section class=split>

<section class=split-item>
<h2 class=header>Branches</h2>
<%= form_for @update_branches, project_path(@conn, :update_branches, @project), [as: :project], fn f -> %>
  <label for=staging_branch>staging</label>
  <%= text_input f, :staging_branch, id: "staging_branch" %>
  <label for=trying_branch>trying</label>
  <%= text_input f, :trying_branch, id: "trying_branch" %>
  <div class=toolbar><%= submit "Update", class: "toolbar-item" %></div>
<% end %>
</section> <!-- class=split-item -->

<section class=split-item>
<h2 class=header>Bors Badge</h2>
<p>Put this badge in your README to show your love for Bors.</p>
<p><a href="<%= project_url(@conn, :show, @project) %>"><img src="https://bors.tech/images/badge_small.svg" alt="Bors enabled"></a></p>
<h3 class=header>HTML</h3>
<textarea rows="5" cols="50" onclick="this.focus();this.select()" readonly="readonly">
<a href="<%= project_url(@conn, :show, @project) %>"><img src="https://bors.tech/images/badge_small.svg" alt="Bors enabled"></a>
</textarea>
<h3 class=header>Markdown</h3>
<textarea rows="5" cols="50" onclick="this.focus();this.select()" readonly="readonly">
[![Bors enabled](https://bors.tech/images/badge_small.svg)](<%= project_url(@conn, :show, @project) %>)
</textarea>

</section> <!-- class=split-item -->

</section></div> <!-- class=split -->

</main>

lib/web/templates/project/show.html.eex
<nav>
<div class=wrapper>
  <h1>
    <a href="<%= Confex.fetch_env!(:bors, :html_github_root) %>/<%= @project.name %>/">
      <%= @project.name %>
    </a>
  </h1>
</div>
<div class=tabs role=navigation>
  <span class="tab tab--active" aria-selected=true>Pull requests</span>
  <%= if @mode == :rw do %>
  <%= link "History", to: project_path(@conn, :log, @project), class: "tab" %>
  <%= link "Settings", to: project_path(@conn, :settings, @project), class: "tab" %>
  <% end %>
</div>
</nav>

<main role=main><div class=wrapper>

<%= if empty?(@unbatched_patches) and empty?(@batches) do %>
  Nothing to see here
<% else %>
<table class="table">
<%= for batch <- @batches do %>
  <thead>
    <tr role=heading><td aria-role=presentation colspan=4>
      <h2 class=header>
        <%= stringify_state batch.state %>
        <span class=header-count><%= Enum.count(batch.patches) %></span>
      </h2>
    </td></tr>
    <tr role=row><th>#</th><th>Title</th><th>Priority</th><th>Commit</th></tr>
  </thead>
  <tbody>
  <%= for patch <- batch.patches do %>
    <tr role="row">
      <td>
        <%= patch.pr_xref %>
      </td>
      <td class="fill-link">
        <a href="<%= Confex.fetch_env!(:bors, :html_github_root) %>/<%= @project.name %>/pull/<%= patch.pr_xref %>">
          <%= patch.title %>
        </a>
      </td>
      <td>
        <%= patch.priority %>
      </td>
      <td>
        <%= truncate_commit(patch.commit) %>
      </td>
    </tr>
  <% end %>
  </tbody>
<% end %>
<%= if @unbatched_patches != [] do %>
  <thead>
    <tr role=heading><td aria-role=presentation colspan=4>
      <h2 class=header>
        Awaiting review
        <span class=header-count><%= Enum.count(@unbatched_patches) %></span>
      </h2>
    </td></tr>
    <tr role=row><th>#</th><th>Title</th><th>Priority</th><th>Commit</th></tr>
  </thead>
  <tbody>
  <%= for patch <- @unbatched_patches do %>
    <tr role="row">
      <td>
        <%= patch.pr_xref %>
      </td>
      <td class="fill-link">
        <a href="<%= Confex.fetch_env!(:bors, :html_github_root) %>/<%= @project.name %>/pull/<%= patch.pr_xref %>">
          <%= patch.title %>
        </a>
      </td>
      <td>
        <%= patch.priority %>
      </td>
      <td>
        <%= truncate_commit(patch.commit) %>
      </td>
    </tr>
  <% end %>
  </tbody>
<% end %>
</table>
<% end %>

</div></main>

<%= if @mode == :rw do %>
<footer><div class="wrapper wrapper--mini" role=toolbar><div class=toolbar>
<%= if @is_synchronizing do %>
  <span class="toolbar-item toolbar-item--disabled">Synchronizing...</span>
<% else %>
  <%= link "Sync pull requests", to: project_path(@conn, :synchronize, @project), method: :put, class: "toolbar-item" %>
<% end %>
<%= if @batches != [] do %>
  <%= link "Cancel all", to: project_path(@conn, :cancel_all, @project), method: :delete, class: "toolbar-item toolbar-item--remove", data: [confirm: "Commenting `bors r-` on a PR will cancel just the one. You asked to cancel all of them, which is a PITA to undo.\n\nAre you sure you want to cancel all running and waiting pull requests?"] %>
<% end %>
</div></div></footer>
<% end %>